springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:mem:pruebadb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secret-key: b2VjTm00dTd6ZQ==
  expiration-millis: 600000L
user:
  password:
    regex: '^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$'
server:
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
    include-binding-errors: always